version: '3'

services:
  api:
    build: .
    command: npm run start:dev
    restart: always
    ports:
      - $API_PORT:3000
    volumes:
      - .:/home/app
      - /home/app/node_modules
    environment:
      - JWT_SECRET
      - MONGO_URI
      - APP_NAME
      - APP_VERSION
      - FILE_HOST
  
  db:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
    volumes:
      - db:/data/db

  admin:
    image: mongo-express
    restart: always
    ports:
      - $ADMIN_PORT:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_INITDB_ROOT_USERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - ME_CONFIG_MONGODB_URL=$MONGO_URI
    depends_on:
      - db

  files:
    image: nginx:alpine
    restart: always
    volumes:
      - ./files:/usr/share/nginx/html
    ports:
      - $FILE_PORT:80

volumes:
  db:
